### ISSUE TITLE
Possible worth filtering the list of tables 

### ISSUE THREAD

**Issue by barryhunter** [webigorkiev/indexbackup#1]
https://github.com/webigorkiev/indexbackup/blob/3b0ac5bca3dd2443d12422b0b65e97cdff8eb453/src/index.ts#L60

... might be ok for most users just using the output of SHOW TABLES directly. Particular is using RT mode, probably only have RT indexes (and maybe percolate). 

But some users might be using multiple types, in particular shouldn't backup 'distributed' and 'template' indexes. Although in practice it might be ok, as they wont have any files in the output of `LOCK TABLE`s anyway. 
... ie your script just backups the files that the server tells it about!

Plain indexes are a bit more in the middle, in general wouldn't need to backup them - as can usually be recreated ondemand. But still might want to back them up (for quick restore) and/or might still be updating the attributes on a live index. (So do want to backup attributes, even if dont need to backup attributes. 

Simplest might to have two versions of 'all' with (so rt,percolate&plain) and without plain (which would be just rt+percolate)

**Comment by webigorkiev** [comment]
Added in version [0.0.9](https://github.com/webigorkiev/indexbackup/tree/v0.0.9)
