### ISSUE TITLE
Include manticore.json and maybe manticore.conf

### ISSUE THREAD

**Issue by barryhunter** [webigorkiev/indexbackup#2]
On the --all option, which appears to be intended to a backup of the 'whole server', should include manticore.json (from the datadir directory) - as would need to to be able to restore. (otherwise would have to manually create a list of indexes to recreate manticore.json to restore)

Or suppose could just backup manticore.json separately, but seems it should be in the backup tar file. 

... at least if using RT mode. If using plain mode, have a list of indexes in manticore.conf file, so should backup that instead. 

(could backup manticore.conf in both modes, less critical for RT mode, but might still have some settings needed)

**Comment by webigorkiev** [comment]
Added in version [0.0.9](https://github.com/webigorkiev/indexbackup/tree/v0.0.9)

**Comment by webigorkiev** [comment]
Yes, it seems to be necessary in some cases.
Unfortunately there is currently no way to get the path to manticore's data directory.
(And accordingly to the manticore.json file)

In configuration:
data_dir = /var/lib/manticore

**Comment by barryhunter** [comment]
Oh, thats a good point. 

If you know the server is in RT-mode, I suppose you could deduce the path to manticore.json from one of the index files. Ie the .json file will just be in the same folder as the indexes. (ie they just all put in data_dir) 

but even knowing you in RT mode (just from output of SHOW STATUS/VARIABLES for exmaple) isnt easy. 

Hopefully data_dir, and even the path to config file could be added to SHOW STATUS.

**Comment by webigorkiev** [comment]
Resolved in [0.0.10](https://github.com/webigorkiev/indexbackup/tree/v0.1.0)
When there will be an official decision on selecting data_dir - it will be necessary to return to this
